---
- name: Install nginx
  apt: name=nginx state=latest

- name: Copy supervisord configuration
  template: src=supervisor-nginx.conf dest=/etc/supervisor/conf.d/supervisor-nginx.conf
  notify: 
    - update programs
    - start nginx

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx